server:
  port: 7070
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Toshibby/ms-altitexti-spring.git # ruta del repositorio git
          searchPaths: config-data
          default-label: main