spring:
  application:
    name: ms-producto
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070
#spring:
#  application:
#    name: ms-producto
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/ms_altitexti_producto?useSSL=false&serverTimezone=UTC
#    username: root
#    password: topgym123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#server:
#  port: 8082
#
## Swagger OpenAPI
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /doc/swagger-ui.html


## ===============================
## CONFIGURACIÓN DE LA BASE DE DATOS
## ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/ms_altitexti_producto?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=topgym123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## ===============================
## CONFIGURACIÓN DE JPA / HIBERNATE
## ===============================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#
## ===============================
## PUERTO DEL SERVICIO
## ===============================
#server.port=8082
#
## Nombre del microservicio (para Eureka si usas discovery)
#spring.application.name=ms-producto
#
## Swagger OpenAPI
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/doc/swagger-ui.html