spring:
  application:
    name: ms-cliente
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:7070
#spring:
#  application:
#    name: ms-cliente
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/ms_altitexti_cliente?useSSL=false&serverTimezone=UTC
#    username: root
#    password: topgym123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#server:
#  port: 8084
#
## Swagger OpenAPI
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /doc/swagger-ui.html


#spring.application.name=ms-cliente
## ===============================
## Configuración del servidor
## ===============================
#server.port=8083
#
## ===============================
## Configuración de la base de datos
## ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/ms_altitexti_cliente?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=topgym123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## ===============================
## Configuración de JPA/Hibernate
## ===============================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#
## Swagger OpenAPI
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/doc/swagger-ui.html
